version: '3.2'
services:
  db:
    image: mongo:3.4-jessie
    volumes:
      - type: volume
        source: mongo_db
        target: /data/db
        volume:
          nocopy: true
      - type: volume
        source: mongo_configdb
        target: /data/configdb
        volume:
          nocopy: true
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - workshop_api_network
  app:
    depends_on:
      - db
    image: workshop_api
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /opt/app
    networks:
      - workshop_api_network
    ports:
      - "0.0.0.0:55555:3000"

volumes:
  mongo_db:
  mongo_configdb:
networks:
  workshop_api_network:
